apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: h64ucns2y-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:f5b99f2d6e8d77489e36df5451d9b62bf59d8195@sha256:518135f69e9a577529da494082aaeb5f0ef447894ceddf36a8e76b50a63ebbc0
          name: container-image
